#pragma once

#include "simplegl.h"
#include "compiler_settings.h"

#include "program.hpp"
#include "object.hpp"
#include "properties.hpp"
#include "obj3dPG.hpp"
#include "obj3d_ipg.hpp"
#include "obj3dBP.hpp"
#include "obj3d.hpp"
#include "misc.hpp"
#include "math.hpp"
#include "cam.hpp"
#include "texture.hpp"
#include "skyboxPG.hpp"
#include "skybox.hpp"
#include "glfw.hpp"
#include "behavior.hpp"
#include "behaviormanaged.hpp"
#include "transformBH.hpp"
#include "fps.hpp"
#include "framebuffer.hpp"
#include "gamemanager.hpp"
#include "text_pg.hpp"
#include "uipanel.hpp"
#include "lod_manager.hpp"
